export const mockUsers = [
  { id: 1, username: "anson", displayName: "Anson" },
  { id: 2, username: "nina", displayName: "Nina" },
  { id: 3, username: "mike", displayName: "Mike" },
  { id: 4, username: "julia", displayName: "Julia" },
  { id: 5, username: "ethan", displayName: "Ethan" },
  { id: 6, username: "claire", displayName: "Claire" },
  { id: 7, username: "kevin", displayName: "Kevin" },
  { id: 8, username: "hannah", displayName: "Hannah" },
  { id: 9, username: "diana", displayName: "Diana" },
  { id: 10, username: "paula", displayName: "Paula" },
  { id: 11, username: "steve", displayName: "Steve" },
  { id: 12, username: "fiona", displayName: "Fiona" },
  { id: 13, username: "brad", displayName: "Brad" },
  { id: 14, username: "ursula", displayName: "Ursula" },
  { id: 15, username: "george", displayName: "George" },
  { id: 16, username: "oliver", displayName: "Oliver" },
  { id: 17, username: "ian", displayName: "Ian" },
  { id: 18, username: "rachel", displayName: "Rachel" },
  { id: 19, username: "quentin", displayName: "Quentin" },
  { id: 20, username: "tina", displayName: "Tina" },
  { id: 21, username: "linda", displayName: "Linda" },
];
